version: '3'
services:

  mqtt-nmea:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_TOPIC_NMEA_IN=CROWSNEST/SEAHORSE/NMEA0183/WIND
      - MQTT_TOPIC_JSON_OUT=CROWSNEST/SEAHORSE/WIND/0/JSON
