# generated by datamodel-codegen:
#   filename:  envelope.json
#   timestamp: 2022-10-17T06:09:47+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra, Field


class Envelope(BaseModel):
    class Config:
        extra = Extra.forbid

    sent_at: datetime = Field(
        ...,
        description='Date and time when the message was sent from the application processing the sensor data, expressed according to the ISO 8601 standard.',
        examples=['2021-10-07T20:20:39.345+00:00'],
        title='Sent at',
    )
    message: Union[float, str, bool, Dict[str, Any], List[Any]] = Field(
        ..., description='The message contained by this envelope.', title='Message'
    )
