# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    - name: Download meta schema
      run: wget -O meta_schema.json http://json-schema.org/draft/2020-12/schema
    - name: Check validity of json schemas
      run: |
        jsonschema -i envelope.json meta_schema.json
        for f in messages/*.json; do echo $f; jsonschema -i $f meta_schema.json; done
        for f in descriptions/*.json; do echo $f; jsonschema -i $f meta_schema.json; done
        for f in descriptions/*/*.json; do echo $f; jsonschema -i $f meta_schema.json; done

  model_generation:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datamodel-code-generator[http]
    - name: Check that we can generate pydantic models from the schemas
      run: |
        datamodel-codegen --input envelope.json --input-file-type jsonschema --output envelope.py
        datamodel-codegen --input messages --input-file-type jsonschema  --reuse-model --output messages_output
        datamodel-codegen --input descriptions --input-file-type jsonschema  --reuse-model --output descriptions_output