name: Publish docs

on:
  release:
    types: [published]

jobs:
    docs: 
      name: Push specs to github pages
      runs-on: "ubuntu-latest"
      steps: 
        - uses: actions/checkout@v2

        - name: Copy files
          run: |
            mkdir publish
            cp envelope.json publish/
            cp -R messages/ publish/
        - name: Publish
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: publish/
            destination_dir: ${{ github.event.release.tag_name }}