# generated by datamodel-codegen:
#   filename:  angle_rate.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AngleRate(BaseModel):
    __root__: float = Field(
        ..., description='Angular rate reading [deg/min]', title='Angle rate'
    )
