# generated by datamodel-codegen:
#   filename:  attitude.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Attitude(BaseModel):
    __root__: List[float] = Field(
        ...,
        description="Attitude [Yaw, Pitch, Roll] (radians) of a body with respect to the body's NED frame of reference.",
        max_items=3,
        min_items=3,
        title='Attitude',
    )
