# generated by datamodel-codegen:
#   filename:  error_ellipse.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ErrorEllipse(BaseModel):
    semi_major_axis: float = Field(
        ...,
        description="Semi-major axis of the GNSS sensor's error ellipse for 1 standard deviation",
        title='Semi-major axis',
    )
    semi_minor_axis: float = Field(
        ...,
        description="Semi-minor axis of the GNSS sensor's error ellipse for 1 standard deviation",
        title='Semi-minor axis',
    )
    azimuth: float = Field(
        ...,
        description="Azimuth of the semi-major axis of the GNSS sensor's error ellipse with respect to True North in degrees",
        title='Azimuth',
    )
