# generated by datamodel-codegen:
#   filename:  playback.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PlaybackCommand(BaseModel):
    playback_speed: float = Field(
        ...,
        description='Reverse is number under zero. Zero is paused. Above zero is moving forward and 1 is seen as normal speed',
        title='Playback speed',
    )
    start_from: Optional[float] = Field(
        None,
        description='Start frame where position from where the playback will start or continue from',
        title='Start from',
    )
