# generated by datamodel-codegen:
#   filename:  point_cloud.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class PointCloud(BaseModel):
    __root__: List = Field(
        ...,
        description='A cloud of 3D points as a list of (x,y,z) tuples [m] in a right-handed, cartesian frame of reference.',
        examples=[[0.0, 0.0, 0.0], [0.0, 1.0, 0.0]],
        title='Point cloud',
    )
