# generated by datamodel-codegen:
#   filename:  position.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Position(BaseModel):
    __root__: List[float] = Field(
        ...,
        description='Position [longitude, latitude, altitude] [degrees, degrees, m] of a body with respect to the WGS84 frame of reference. Altitude is the height of the body above the WGS84 ellipsoid.',
        max_items=3,
        min_items=3,
        title='Position',
    )
