# generated by datamodel-codegen:
#   filename:  speed.json
#   timestamp: 2022-10-17T06:10:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Speed(BaseModel):
    __root__: float = Field(..., description='Speed reading [knots]', title='Speed')
